version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      MONGODB_URL: mongodb://mongo_db:27017/todo_app
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}